package com.serviceapp.mapping;
// Generated Mar 27, 2018 3:32:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MobAudittrace generated by hbm2java
 */
@Entity
@Table(name="mob_audittrace"
    ,catalog="service_app"
)
public class MobAudittrace  implements java.io.Serializable {


     private Integer id;
     private String username;
     private Integer userid;
     private String type;
     private String operation;
     private String ip;
     private String device;
     private String description;
     private Date createdtime;

    public MobAudittrace() {
    }

    public MobAudittrace(String username, Integer userid, String type, String operation, String ip, String device, String description, Date createdtime) {
       this.username = username;
       this.userid = userid;
       this.type = type;
       this.operation = operation;
       this.ip = ip;
       this.device = device;
       this.description = description;
       this.createdtime = createdtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="USERNAME", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="USERID")
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    
    @Column(name="TYPE", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="OPERATION", length=1024)
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }

    
    @Column(name="IP", length=64)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="DEVICE", length=256)
    public String getDevice() {
        return this.device;
    }
    
    public void setDevice(String device) {
        this.device = device;
    }

    
    @Column(name="DESCRIPTION", length=4000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=10)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


