package com.serviceapp.mapping;
// Generated Apr 16, 2018 6:02:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MobBassRatings generated by hbm2java
 */
@Entity
@Table(name="mob_bass_ratings"
    ,catalog="service_app"
)
public class MobBassRatings  implements java.io.Serializable {


     private Long id;
     private MobBassData mobBassData;
     private MobServiceRequest mobServiceRequest;
     private MobUser mobUser;
     private int rating;
     private Date createdTime;

    public MobBassRatings() {
    }

    public MobBassRatings(MobBassData mobBassData, MobServiceRequest mobServiceRequest, MobUser mobUser, int rating, Date createdTime) {
       this.mobBassData = mobBassData;
       this.mobServiceRequest = mobServiceRequest;
       this.mobUser = mobUser;
       this.rating = rating;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bass_id", nullable=false)
    public MobBassData getMobBassData() {
        return this.mobBassData;
    }
    
    public void setMobBassData(MobBassData mobBassData) {
        this.mobBassData = mobBassData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id", nullable=false)
    public MobServiceRequest getMobServiceRequest() {
        return this.mobServiceRequest;
    }
    
    public void setMobServiceRequest(MobServiceRequest mobServiceRequest) {
        this.mobServiceRequest = mobServiceRequest;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public MobUser getMobUser() {
        return this.mobUser;
    }
    
    public void setMobUser(MobUser mobUser) {
        this.mobUser = mobUser;
    }

    
    @Column(name="rating", nullable=false)
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


