package com.serviceapp.mapping;
// Generated Apr 16, 2018 6:02:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MobBassLevelConfig generated by hbm2java
 */
@Entity
@Table(name="mob_bass_level_config"
    ,catalog="service_app"
    , uniqueConstraints = @UniqueConstraint(columnNames="required_service_count") 
)
public class MobBassLevelConfig  implements java.io.Serializable {


     private String level;
     private String description;
     private double price;
     private int requiredServiceCount;
     private Set<MobBassData> mobBassDatas = new HashSet(0);

    public MobBassLevelConfig() {
    }

	
    public MobBassLevelConfig(String level, String description, double price, int requiredServiceCount) {
        this.level = level;
        this.description = description;
        this.price = price;
        this.requiredServiceCount = requiredServiceCount;
    }
    public MobBassLevelConfig(String level, String description, double price, int requiredServiceCount, Set<MobBassData> mobBassDatas) {
       this.level = level;
       this.description = description;
       this.price = price;
       this.requiredServiceCount = requiredServiceCount;
       this.mobBassDatas = mobBassDatas;
    }
   
     @Id 

    
    @Column(name="level", unique=true, nullable=false, length=20)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    
    @Column(name="description", nullable=false, length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="required_service_count", unique=true, nullable=false)
    public int getRequiredServiceCount() {
        return this.requiredServiceCount;
    }
    
    public void setRequiredServiceCount(int requiredServiceCount) {
        this.requiredServiceCount = requiredServiceCount;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="mobBassLevelConfig")
    public Set<MobBassData> getMobBassDatas() {
        return this.mobBassDatas;
    }
    
    public void setMobBassDatas(Set<MobBassData> mobBassDatas) {
        this.mobBassDatas = mobBassDatas;
    }




}


