package com.serviceapp.mapping;
// Generated Mar 30, 2018 8:48:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MobConfiguration generated by hbm2java
 */
@Entity
@Table(name="mob_configuration"
    ,catalog="service_app"
)
public class MobConfiguration  implements java.io.Serializable {


     private int code;
     private String description;
     private String value;

    public MobConfiguration() {
    }

	
    public MobConfiguration(int code) {
        this.code = code;
    }
    public MobConfiguration(int code, String description, String value) {
       this.code = code;
       this.description = description;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="VALUE")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


