package com.serviceapp.mapping;
// Generated Apr 2, 2018 9:41:58 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MobFaqSection generated by hbm2java
 */
@Entity
@Table(name="mob_faq_section"
    ,catalog="service_app"
)
public class MobFaqSection  implements java.io.Serializable {


     private String sectionType;
     private String description;
     private Set<MobFaq> mobFaqs = new HashSet(0);

    public MobFaqSection() {
    }

	
    public MobFaqSection(String sectionType) {
        this.sectionType = sectionType;
    }
    public MobFaqSection(String sectionType, String description, Set<MobFaq> mobFaqs) {
       this.sectionType = sectionType;
       this.description = description;
       this.mobFaqs = mobFaqs;
    }
   
     @Id 

    
    @Column(name="section_type", unique=true, nullable=false, length=50)
    public String getSectionType() {
        return this.sectionType;
    }
    
    public void setSectionType(String sectionType) {
        this.sectionType = sectionType;
    }

    
    @Column(name="description", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mobFaqSection")
    public Set<MobFaq> getMobFaqs() {
        return this.mobFaqs;
    }
    
    public void setMobFaqs(Set<MobFaq> mobFaqs) {
        this.mobFaqs = mobFaqs;
    }




}


