package com.serviceapp.mapping;
// Generated Mar 26, 2018 11:25:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MobFaq generated by hbm2java
 */
@Entity
@Table(name="mob_faq"
    ,catalog="service_app"
)
public class MobFaq  implements java.io.Serializable {


     private Integer id;
     private MobFaqType mobFaqType;
     private Status status;
     private String question;
     private String answer;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private String section;

    public MobFaq() {
    }

    public MobFaq(MobFaqType mobFaqType, Status status, String question, String answer, String lastupdateduser, Date lastupdatedtime, Date createdtime, String section) {
       this.mobFaqType = mobFaqType;
       this.status = status;
       this.question = question;
       this.answer = answer;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.section = section;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE")
    public MobFaqType getMobFaqType() {
        return this.mobFaqType;
    }
    
    public void setMobFaqType(MobFaqType mobFaqType) {
        this.mobFaqType = mobFaqType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="QUESTION", length=1000)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="ANSWER", length=1000)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDTIME", length=10)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=10)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="SECTION", length=50)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }




}


