package com.serviceapp.mapping;
// Generated Mar 26, 2018 11:25:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MobFaqType generated by hbm2java
 */
@Entity
@Table(name="mob_faq_type"
    ,catalog="service_app"
)
public class MobFaqType  implements java.io.Serializable {


     private String code;
     private String description;
     private Set<MobFaq> mobFaqs = new HashSet(0);

    public MobFaqType() {
    }

	
    public MobFaqType(String code) {
        this.code = code;
    }
    public MobFaqType(String code, String description, Set<MobFaq> mobFaqs) {
       this.code = code;
       this.description = description;
       this.mobFaqs = mobFaqs;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mobFaqType")
    public Set<MobFaq> getMobFaqs() {
        return this.mobFaqs;
    }
    
    public void setMobFaqs(Set<MobFaq> mobFaqs) {
        this.mobFaqs = mobFaqs;
    }




}


