package com.serviceapp.mapping;
// Generated Jun 5, 2018 10:42:59 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MobServiceCharge generated by hbm2java
 */
@Entity
@Table(name="mob_service_charge"
    ,catalog="service_app"
)
public class MobServiceCharge  implements java.io.Serializable {


     private long serviceId;
     private MobServiceRequest mobServiceRequest;
     private Date createdTime;
     private Date updatedTime;
     private BigDecimal charge;
     private String elapsedTime;

    public MobServiceCharge() {
    }

	
    public MobServiceCharge(MobServiceRequest mobServiceRequest, Date createdTime, Date updatedTime, String elapsedTime) {
        this.mobServiceRequest = mobServiceRequest;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.elapsedTime = elapsedTime;
    }
    public MobServiceCharge(MobServiceRequest mobServiceRequest, Date createdTime, Date updatedTime, BigDecimal charge, String elapsedTime) {
       this.mobServiceRequest = mobServiceRequest;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
       this.charge = charge;
       this.elapsedTime = elapsedTime;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="mobServiceRequest"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="service_id", unique=true, nullable=false)
    public long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(long serviceId) {
        this.serviceId = serviceId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public MobServiceRequest getMobServiceRequest() {
        return this.mobServiceRequest;
    }
    
    public void setMobServiceRequest(MobServiceRequest mobServiceRequest) {
        this.mobServiceRequest = mobServiceRequest;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false, length=19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    
    @Column(name="charge", precision=20)
    public BigDecimal getCharge() {
        return this.charge;
    }
    
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    
    @Column(name="elapsed_time", nullable=false, length=16777215)
    public String getElapsedTime() {
        return this.elapsedTime;
    }
    
    public void setElapsedTime(String elapsedTime) {
        this.elapsedTime = elapsedTime;
    }




}


