package com.serviceapp.mapping;
// Generated Apr 4, 2018 10:44:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MobSuggestedUser generated by hbm2java
 */
@Entity
@Table(name="mob_suggested_user"
    ,catalog="service_app"
    , uniqueConstraints = @UniqueConstraint(columnNames="mobile") 
)
public class MobSuggestedUser  implements java.io.Serializable {


     private Long id;
     private MobUser mobUser;
     private Status status;
     private String firstName;
     private String lastName;
     private String email;
     private String area;
     private String serviceRole;
     private String mobile;
     private Date createdTime;

    public MobSuggestedUser() {
    }

	
    public MobSuggestedUser(Status status, String firstName, String area, String mobile, Date createdTime) {
        this.status = status;
        this.firstName = firstName;
        this.area = area;
        this.mobile = mobile;
        this.createdTime = createdTime;
    }
    public MobSuggestedUser(MobUser mobUser, Status status, String firstName, String lastName, String email, String area, String serviceRole, String mobile, Date createdTime) {
       this.mobUser = mobUser;
       this.status = status;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.area = area;
       this.serviceRole = serviceRole;
       this.mobile = mobile;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="referrer")
    public MobUser getMobUser() {
        return this.mobUser;
    }
    
    public void setMobUser(MobUser mobUser) {
        this.mobUser = mobUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="first_name", nullable=false, length=64)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=128)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=128)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="area", nullable=false, length=64)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="service_role", length=64)
    public String getServiceRole() {
        return this.serviceRole;
    }
    
    public void setServiceRole(String serviceRole) {
        this.serviceRole = serviceRole;
    }

    
    @Column(name="mobile", unique=true, nullable=false, length=12)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


