package com.serviceapp.mapping;
// Generated Jun 5, 2018 10:42:59 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MobScheduledServiceRequest generated by hbm2java
 */
@Entity
@Table(name="mob_scheduled_service_request"
    ,catalog="service_app"
)
public class MobScheduledServiceRequest  implements java.io.Serializable {


     private Long id;
     private MobUser mobUser;
     private Roles roles;
     private Date scheduledDateTime;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String description;
     private Date createdTime;
     private String address;

    public MobScheduledServiceRequest() {
    }

	
    public MobScheduledServiceRequest(MobUser mobUser, Roles roles, Date scheduledDateTime, BigDecimal latitude, BigDecimal longitude, Date createdTime) {
        this.mobUser = mobUser;
        this.roles = roles;
        this.scheduledDateTime = scheduledDateTime;
        this.latitude = latitude;
        this.longitude = longitude;
        this.createdTime = createdTime;
    }
    public MobScheduledServiceRequest(MobUser mobUser, Roles roles, Date scheduledDateTime, BigDecimal latitude, BigDecimal longitude, String description, Date createdTime, String address) {
       this.mobUser = mobUser;
       this.roles = roles;
       this.scheduledDateTime = scheduledDateTime;
       this.latitude = latitude;
       this.longitude = longitude;
       this.description = description;
       this.createdTime = createdTime;
       this.address = address;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public MobUser getMobUser() {
        return this.mobUser;
    }
    
    public void setMobUser(MobUser mobUser) {
        this.mobUser = mobUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bass_type", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="scheduled_date_time", nullable=false, length=19)
    public Date getScheduledDateTime() {
        return this.scheduledDateTime;
    }
    
    public void setScheduledDateTime(Date scheduledDateTime) {
        this.scheduledDateTime = scheduledDateTime;
    }

    
    @Column(name="latitude", nullable=false, precision=10, scale=8)
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=11, scale=8)
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="address", length=16777215)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


