package com.serviceapp.mapping;
// Generated Mar 19, 2018 7:41:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="service_app"
)
public class Status  implements java.io.Serializable {


     private String statuscode;
     private String category;
     private String description;
     private Set<Systemuser> systemusers = new HashSet(0);

    public Status() {
    }

	
    public Status(String statuscode) {
        this.statuscode = statuscode;
    }
    public Status(String statuscode, String category, String description, Set<Systemuser> systemusers) {
       this.statuscode = statuscode;
       this.category = category;
       this.description = description;
       this.systemusers = systemusers;
    }
   
     @Id 

    
    @Column(name="STATUSCODE", unique=true, nullable=false, length=10)
    public String getStatuscode() {
        return this.statuscode;
    }
    
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    
    @Column(name="CATEGORY", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Systemuser> getSystemusers() {
        return this.systemusers;
    }
    
    public void setSystemusers(Set<Systemuser> systemusers) {
        this.systemusers = systemusers;
    }




}


