package com.serviceapp.mapping;
// Generated Mar 19, 2018 7:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systemaudit generated by hbm2java
 */
@Entity
@Table(name="web_systemaudit"
    ,catalog="service_app"
)
public class Systemaudit  implements java.io.Serializable {


     private Integer systemauditid;
     private String description;
     private String section;
     private String page;
     private String task;
     private String remarks;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private String newvalue;
     private String oldvalue;
     private Date createtime;

    public Systemaudit() {
    }

    public Systemaudit(String description, String section, String page, String task, String remarks, String lastupdateduser, Date lastupdatedtime, String newvalue, String oldvalue, Date createtime) {
       this.description = description;
       this.section = section;
       this.page = page;
       this.task = task;
       this.remarks = remarks;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.newvalue = newvalue;
       this.oldvalue = oldvalue;
       this.createtime = createtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SYSTEMAUDITID", unique=true, nullable=false)
    public Integer getSystemauditid() {
        return this.systemauditid;
    }
    
    public void setSystemauditid(Integer systemauditid) {
        this.systemauditid = systemauditid;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SECTION")
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }

    
    @Column(name="PAGE")
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }

    
    @Column(name="TASK")
    public String getTask() {
        return this.task;
    }
    
    public void setTask(String task) {
        this.task = task;
    }

    
    @Column(name="REMARKS")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="NEWVALUE", length=4000)
    public String getNewvalue() {
        return this.newvalue;
    }
    
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }

    
    @Column(name="OLDVALUE", length=4000)
    public String getOldvalue() {
        return this.oldvalue;
    }
    
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATETIME", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}
