package com.serviceapp.mapping;
// Generated Apr 4, 2018 10:44:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name="user_roles"
    ,catalog="service_app"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "role_type"}) 
)
public class UserRoles  implements java.io.Serializable {


     private Long id;
     private MobUser mobUser;
     private String roleType;
     private String status;

    public UserRoles() {
    }

    public UserRoles(MobUser mobUser, String roleType, String status) {
       this.mobUser = mobUser;
       this.roleType = roleType;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public MobUser getMobUser() {
        return this.mobUser;
    }
    
    public void setMobUser(MobUser mobUser) {
        this.mobUser = mobUser;
    }

    
    @Column(name="role_type", nullable=false, length=16)
    public String getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


