package com.serviceapp.mapping;
// Generated Mar 26, 2018 2:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebSmsTemplate generated by hbm2java
 */
@Entity
@Table(name="web_sms_template"
    ,catalog="service_app"
)
public class WebSmsTemplate  implements java.io.Serializable {


     private Integer messageid;
     private TransactionType transactionType;
     private String message;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public WebSmsTemplate() {
    }

    public WebSmsTemplate(TransactionType transactionType, String message, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.transactionType = transactionType;
       this.message = message;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MESSAGEID", unique=true, nullable=false)
    public Integer getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANSACTIONTYPE")
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="MESSAGE", length=1028)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDTIME", length=10)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=10)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


